version: '3'
services:
  php:
    container_name: php
    build: ./php
    volumes:
      - /Users/unamu/Desktop/git/html/php7.2-mysql-nginx/laravel:/var/www/html/laravel
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini


  web:
    container_name: web
    image: nginx:1.13.5-alpine
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - /Users/unamu/Desktop/git/html/php7.2-mysql-nginx/laravel:/var/www/html/laravel

  db:
    container_name: db
    image: mysql:5.7.19
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  elasticsearch:
    build: es
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./es/config:/usr/share/elasticsearch/config
    ports:
      - 9200:9200
    expose:
      - 9300
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    build: kibana
    links:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

volumes:
  db-data:
  es-data: