version: '3'
services:
  php:
    container_name: php
    build: ./php
    volumes:
      - /Users/unamu/Desktop/git/html/php7.2-mysql-nginx/laravel:/var/www/html/laravel

  web:
    container_name: web
    image: nginx:1.13.5-alpine
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - /Users/unamu/Desktop/git/html/php7.2-mysql-nginx/laravel:/var/www/html/laravel

  db:
    container_name: db
    image: mysql:5.7.19
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - /Users/unamu/Desktop/Docker/db:/var/lib/mysql

volumes:
  db-data: